### PR TITLE
chore: remove unused param in func Init

### LINKED ISSUE #2: func Init accepts unused param
Currently function `Init` accepts an unused parameter `logger zerolog.Logger`.

The updated `Init` should ideally look something like this.

```go
func Init() func(logger zerolog.Logger) fxevent.Logger {
	return func(logger zerolog.Logger) fxevent.Logger {
		return &ZeroLogger{Logger: logger}
	}
}
```

There should also probably be another variant of the `Init` function which can be used when the logger constructor returns a `*zerolog.Logger` instead of `zerolog.Logger`.

```go
func InitPtr() func(logger *zerolog.Logger) fxevent.Logger {
	return func(logger *zerolog.Logger) fxevent.Logger {
		return &ZeroLogger{Logger: *logger}
	}
}
```

Should I go ahead and add a PR for these changes?

### PR DESCRIPTION
**Pull request by sounak98**
Fix https://github.com/efectn/fx-zerolog/issues/2

### CODE REVIEW

**Comment by efectn** [comment]
Will you add InitPtr or ill merge it @sounak98

**Comment by sounak98** [comment]
> Will you add InitPtr or ill merge it @sounak98

added

**Comment by efectn** [comment]
Thanks for the contribution ❤️

**Comment by sounak98** [comment]
@efectn will you be making a release soon?

**Comment by efectn** [comment]
> @efectn will you be making a release soon?

Done

**Pull request merged**
